project_id = "hanalytics-terraform"
region = "europe-west1"
zone = "europe-west1-b"
bucket_name = "hanalytics-bucket-tfstate"
machine_type = "e2-micro"
#client_name = "hanalytics"
#tf_service_account = "sa-demo-tf-sbx@PROJECT_ID.iam.gserviceaccount.com"