project_id = "hanalytics-terraform"
table_id = "sales_data"
dataset_id = "my_source_dataset"
source_location = "US"
destination_location = "EU"
bigquery_service_account = "terraform@hanalytics-terraform.iam.gserviceaccount.com"